Latest matplotlib (3.5.2) has bug copying rcParams, setting required version to <=3.5.1 until fixed
File ~/Desktop/fontsize/env/lib/python3.9/site-packages/matplotlib/__init__.py:644, in RcParams.__setitem__(self, key, val)
    642             return
    643 try:
--> 644     cval = self.validate[key](val)
    645 except ValueError as ve:
    646     raise ValueError(f"Key {key}: {ve}") from None

File ~/Desktop/fontsize/env/lib/python3.9/site-packages/matplotlib/rcsetup.py:254, in validate_backend(s)
    252 def validate_backend(s):
    253     backend = (
--> 254         s if s is _auto_backend_sentinel or s.startswith("module://")
    255         else _validate_standard_backends(s))
    256     return backend

AttributeError: 'object' object has no attribute 'startswith'